import { existsSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { SOURCE_RULES } from "../../lint/source.js";
import { RULES } from "../../lint/timeline.js";
import { emphasisPresets, enterPresets, exitPresets, type PresetDef } from "../../motion/presets.js";
import { durations, eases, staggers } from "../../motion/tokens.js";
import { TRANSITION_DEFS } from "../../motion/transitions.js";
import { PKG_ROOT, rel } from "../../paths.js";
import { TYPE_SCALE } from "../../build/css.js";
import { themes } from "../../themes/index.js";
import { typeKits, type RoleStyle } from "../../themes/kits.js";
import type { Command } from "../lib/command.js";
import { flagBool } from "../lib/args.js";
import { log, ok } from "../lib/log.js";

function presetRows(defs: Record<string, PresetDef>): string {
  return Object.entries(defs)
    .map(([name, d]) => {
      const segs = d.segments({});
      const props = [...new Set(segs.flatMap((s) => Object.keys(s.props)))].join(", ");
      const s0 = segs[0];
      const dur = typeof s0.duration === "number" ? `${s0.duration}s` : `${s0.duration} (${durations[s0.duration]}s)`;
      return `| \`${name}\` | ${props} | ${dur} | ${s0.ease} | ${d.mask ? "yes" : ""} | ${d.description} |`;
    })
    .join("\n");
}

const roleLine = (r: RoleStyle) =>
  `${r.family.family} ${r.weight}${r.width !== undefined && r.width !== 100 ? ` w${r.width}` : ""}${r.axes ? ` ${Object.entries(r.axes).map(([a, v]) => `${a} ${v}`).join(" ")}` : ""}${r.case ? " caps" : ""}`;

export function catalog(): string {
  const head = "| Preset | Animates | Duration | Ease | Mask | Use |\n|---|---|---|---|---|---|";
  return `<!-- generated by \`npx ct docs\` from the engine source — do not edit by hand -->
# Catalog

## Durations
${Object.entries(durations).map(([k, v]) => `- \`${k}\` ${v}s`).join("\n")}

## Eases
${Object.entries(eases)
  .map(([k, v]) => `- \`${k}\` — ${v.type === "bezier" ? `cubic-bezier(${v.p.join(", ")})` : v.type === "spring" ? `spring(stiffness ${v.stiffness}, damping ${v.damping}, mass ${v.mass})` : v.type}`)
  .join("\n")}

## Staggers
${Object.entries(staggers).map(([k, v]) => `- \`${k}\` ${Math.round(v * 1000)}ms`).join("\n")}

## Enter presets
${head}
${presetRows(enterPresets)}

## Exit presets
${head}
${presetRows(exitPresets)}

## Emphasis presets
${head}
${presetRows(emphasisPresets)}

## Scene transitions (storyboard \`transition\`)
| type | default | range | params | what it is |
|---|---|---|---|---|
${Object.entries(TRANSITION_DEFS).map(([k, d]) => `| \`${k}\` | ${k === "cut" ? "—" : `${d.duration}s`} | ${k === "cut" ? "—" : `${d.range[0]}–${d.range[1]}s`} | ${d.params.join(", ") || "—"}${d.dirs && d.dirs.length < 4 ? ` (dir: ${d.dirs.join("/")})` : ""} | ${d.description} |`).join("\n")}

One transition language per video (≤ 2 types besides cuts) — see motion-craft §7.

## Type scale (px at 1080 short side · line-height · tracking)
${Object.entries(TYPE_SCALE).map(([k, [s, lh, ls]]) => `- \`text-${k}\` ${s}px · ${lh} · ${ls}`).join("\n")}

## Themes (colour)
${Object.values(themes).map((t) => `- \`${t.name}\` (${t.mode}) — ${t.description} Suggested kit: \`${t.suggestedType ?? "classic"}\`. Classic fonts: display ${t.fonts.display.family}, sans ${t.fonts.sans.family}, mono ${t.fonts.mono.family}, serif ${t.fonts.serif.family}.`).join("\n")}

## Type kits (storyboard \`type\`)
| kit | evokes | display | text | labels | accent | figures |
|---|---|---|---|---|---|---|
${Object.values(typeKits).map((k) => `| \`${k.name}\` | ${k.evokes} | ${roleLine(k.roles.display)} | ${roleLine(k.roles.sans)} | ${roleLine(k.roles.mono)} ${k.label.case === "uppercase" ? "caps " : ""}${k.label.tracking} | ${k.roles.serif.family.family} ×${k.accent.scale} | ${k.figures} |`).join("\n")}

Omit \`type\` for \`classic\` (the theme's own fonts, v1 settings). Per-kit tracking/leading overrides of the scale:
${Object.values(typeKits).map((k) => `- \`${k.name}\`: ${Object.entries(k.scale).map(([s, [lh, ls]]) => `${s} ${lh}/${ls}`).join(" · ")}`).join("\n")}

## Timeline lint rules
${Object.entries(RULES).map(([k, v]) => `- \`${k}\` — ${v}`).join("\n")}

## Source lint rules
${Object.entries(SOURCE_RULES).map(([k, v]) => `- \`${k}\` — ${v}`).join("\n")}
`;
}

export const docs: Command = {
  name: "docs",
  summary: "Regenerate the skills' catalog (presets, tokens, transitions, themes, lint rules) from the source code.",
  usage: "ct docs [--print]",
  async run(a) {
    const skillDir = join(PKG_ROOT, "plugin/skills/continuity/reference");
    // Outside the Continuity checkout (an installed package) there is no plugin source to update: print instead.
    if (flagBool(a, "print") || !existsSync(skillDir)) {
      log(catalog());
      return 0;
    }
    const out = join(skillDir, "catalog.md");
    writeFileSync(out, catalog());
    ok(`wrote ${rel(out)}`);
    return 0;
  },
};
