import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { RULES } from "../../lint/timeline.js";
import { emphasisPresets, enterPresets, exitPresets, type PresetDef } from "../../motion/presets.js";
import { durations, eases, staggers } from "../../motion/tokens.js";
import { transitionDescriptions } from "../../motion/transitions.js";
import { ROOT, rel } from "../../paths.js";
import { TYPE_SCALE } from "../../build/css.js";
import { themes } from "../../themes/index.js";
import type { Command } from "../lib/command.js";
import { ok } from "../lib/log.js";

function presetRows(defs: Record<string, PresetDef>): string {
  return Object.entries(defs)
    .map(([name, d]) => {
      const segs = d.segments({});
      const props = [...new Set(segs.flatMap((s) => Object.keys(s.props)))].join(", ");
      const s0 = segs[0];
      const dur = typeof s0.duration === "number" ? `${s0.duration}s` : `${s0.duration} (${durations[s0.duration]}s)`;
      return `| \`${name}\` | ${props} | ${dur} | ${s0.ease} | ${d.mask ? "yes" : ""} | ${d.description} |`;
    })
    .join("\n");
}

export function catalog(): string {
  const head = "| Preset | Animates | Duration | Ease | Mask | Use |\n|---|---|---|---|---|---|";
  return `<!-- generated by \`pnpm ct docs\` from src/ — do not edit by hand -->
# Catalog

## Durations
${Object.entries(durations).map(([k, v]) => `- \`${k}\` ${v}s`).join("\n")}

## Eases
${Object.entries(eases)
  .map(([k, v]) => `- \`${k}\` — ${v.type === "bezier" ? `cubic-bezier(${v.p.join(", ")})` : v.type === "spring" ? `spring(stiffness ${v.stiffness}, damping ${v.damping}, mass ${v.mass})` : v.type}`)
  .join("\n")}

## Staggers
${Object.entries(staggers).map(([k, v]) => `- \`${k}\` ${Math.round(v * 1000)}ms`).join("\n")}

## Enter presets
${head}
${presetRows(enterPresets)}

## Exit presets
${head}
${presetRows(exitPresets)}

## Emphasis presets
${head}
${presetRows(emphasisPresets)}

## Scene transitions
${Object.entries(transitionDescriptions).map(([k, v]) => `- \`${k}\` — ${v}`).join("\n")}

## Type scale (px at 1080 short side · line-height · tracking)
${Object.entries(TYPE_SCALE).map(([k, [s, lh, ls]]) => `- \`text-${k}\` ${s}px · ${lh} · ${ls}`).join("\n")}

## Themes
${Object.values(themes).map((t) => `- \`${t.name}\` (${t.mode}) — ${t.description} Fonts: display ${t.fonts.display.family}, sans ${t.fonts.sans.family}, mono ${t.fonts.mono.family}, serif ${t.fonts.serif.family}.`).join("\n")}

## Timeline lint rules
${Object.entries(RULES).map(([k, v]) => `- \`${k}\` — ${v}`).join("\n")}
`;
}

export const docs: Command = {
  name: "docs",
  summary: "Regenerate the skills' catalog (presets, tokens, transitions, themes, lint rules) from the source code.",
  usage: "ct docs",
  async run() {
    const out = join(ROOT, ".claude/skills/continuity/reference/catalog.md");
    writeFileSync(out, catalog());
    ok(`wrote ${rel(out)}`);
    return 0;
  },
};
